org: sybuena
app: luma-integrations
service: etsy-get-products

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getProducts:
    handler: handler.get
    url: true
    environment :
      DB_HOST : '127.0.0.1'
      DB_PORT : '3306'
      DB_DATABASE : 'bagisto_db'
      DB_USERNAME : 'root'
      DB_PASSWORD : 'P@ssw0rds2'
      LARAVEL_API_KEY : 'Px4O9kOtYzcia9Rwnfd26qzS3UgWoimiD6RChawabB0='
      ETSY_API_KEY : ${param:ETSY_KEY}
      STORE_ID : ${param:store_id}
      


